config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'
  
  devise_for :users, controllers: {sessions: 'users/sessions',
                                   omniauth_callbacks: 'users/omniauth_callbacks'}
  root 'home#index'

  namespace :admin do
    get '/dashboard', controller: 'dashboard', action: 'show', as: :dashboard
    get '/grove-monitor', controller: 'grove_monitor', action: 'show', as: :grove_monitor
    get '/grove-monitor-all', controller: 'grove_monitor', action: 'index', as: :grove_monitor_all
    patch '/grove-monitor-all', controller: 'grove_monitor', action: 'update', as: :update_grove_monitor_all
    get '/grove-playlist-manager', controller: 'playlists', action: 'index', as: :grove_playlist_manager
    resources :groves
    resources :locations
    resources :focus_areas
    resources :teachers
    resources :students do
      get '/rebuild_schedule', action: 'rebuild_schedule'
      get '/playlist', controller: 'playlist_activities', action: 'index'
      resources :playlist_activities, except: [:show]
    end
    resources :activities
  end

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      namespace :admin do
        resources :students, only: [] do
          patch '/playlist_activities', controller: 'students/playlist_activities', action: 'update'
        end
      end
    end
  end

  post '/notifications', controller: 'callbacks/google', action: 'watch'

  get '/compass', controller: 'compass', action: 'show', as: :compass
  get '/logout', controller: 'compass', action: 'logout', as: :logout
  get '/checkin', to: 'compass#checkin'

  # sidekiq monitoring
  require 'sidekiq/web'
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/models/users/student.rb
class Student < User
  include Rails.application.routes.url_helpers
  include Redis::Objects

  value :last_activity_id

  has_many :playlist_activities, foreign_key: :user_id, dependent: :destroy
  has_many :events, foreign_key: :user_id, dependent: :destroy
  has_many :scans, foreign_key: :user_id, dependent: :destroy

  scope :absent, -> { where(at_school: false).order(name: :asc) }
  scope :with_access_token, -> { where.not(refresh_token: nil) }
  scope :at_school, -> { where(at_school: true) }

  def admin?
    false
  end

  def after_sign_in_path
    compass_path
  end

  def self.is_student?(data)
    Student.where(email: data["email"]).first
  end

  def self.lost
    self.where.not(id: has_scan_ids)
        .order(name: :asc)
  end

  # @deprecated
  # @param [String] name
  def self.location(name)
  location = Location.find_by(name: name)
  expected_at_location(location.id)
  end

  # this is the list of students that _should_ be at a location currently
  # @param [Integer] location_id
  def self.expected_at_location(location_id)
    self.joins(:events)
        .where(at_school: true)
        .where("start_time <= ? AND end_time >= ?", Time.now, Time.now )
        .where(events: {location_id: location_id})
        .order(name: :asc)
  end

  def self.at_location(location_id)
    has_scan_ids.where('scans.location_id = ?', location_id)
  end

  def self.has_scan_ids
    self.joins(:scans)
        .where(at_school: true)
        .where("scans.scanned_in_at <= ? AND scans.expires_at >= ?", Time.now, Time.now )
  end

  def self.has_event_ids
    self.where(at_school: true)
        .joins(:events)
        .where("start_time <= ? AND end_time >= ?", Time.now, Time.now )
        .pluck(:id)
  end

  def next_position
    max_position = playlist_activities.maximum(:position)
    max_position ? max_position + 1 : 1
  end

  def current_event
    events.where("start_time <= ? AND end_time >= ?", Time.zone.now, Time.zone.now ).first
  end

  def compass_events
    events.where("end_time >= ?", Time.zone.now + Grove::TRANSITION)
          .order(start_time: :asc)
          .limit(2)
  end

  def grove_name
    grove.name
  end

  def scanned_in?
    return false unless current_event
    current_event.scanned_in?
  end

  def last_activity
    scan = scans.includes(:activity)
                .where.not(activity_id: nil)
                .order(created_at: :desc)
                .first
    scan.activity if scan.present?
  end

  def rotated_playlist
    @playlist_activities = playlist_activities.joins(:activity).order('position ASC')
    arr = @playlist_activities.to_a
    offset = arr.index { |x| x.activity.id == last_activity_id.value.to_i } || 0
    arr.rotate!(offset)
  end
end

app/controllers/admin/students_controller.rb
module Admin
  class StudentsController < ResourceController

    def create
      super do |student|
        student.password = student.password_confirmation = SecureRandom.hex
      end
    end

    def rebuild_schedule
      @resource = Student.find(params[:student_id])
      authorize(@resource)
      UpdateScheduleJob.perform_later(@resource.id)
      flash[:notice] = "Student schedule is being rebuilt, it should be ready in a few minutes."
      redirect_to after_save_path_for(@resource)
    end

    protected

    def after_save_path_for(resource)
      admin_students_path
    end

    def whitelist
      [:name, :email, :grove_id]
    end

    def form_attributes
      collection_attributes
    end

    def collection
      current_grove.students.order(name: :asc)
    end

    def collection_attributes
      [:name, :email, :grove_name, :has_refresh_token?]
    end

  end
end

app/controllers/api/v1/admin/students/playlist_activities_controller.rb
module Api
  module V1
    module Admin
      module Students
        class PlaylistActivitiesController < Api::ApiController
          respond_to :json
          skip_before_action :authorize_resource, only: [:update]
          before_action :authorize_collection, only: [:update]
          before_action :set_student

          def update
            @student.playlist_activities.each do |activity|
              activity.update(position: new_position(activity.id))
            end
            respond_with @student
          end
          
          private

            def resource_as_sym
               :playlist_activity
            end 

            def playlist_params
              positions = params[:data].try(:fetch, :positions, {}).keys
              params.require(:data).permit(positions: positions)
            end

            def set_student
              @student = Student.find(params[:student_id])
            end

            def new_position(id)
              playlist_params[:positions][id.to_s]
            end
        end
      end
    end
  end
end

app/views/admin/students/_form.html.erb
<%= simple_form_for([:admin, resource], html: { class: 'inline' }) do |form| %>
  <%= render 'error_notification', form: form %>
  <%= form.input :name %>
  <%= form.input :email %>
  <%= form.input :grove_id, include_blank: false, collection: current_user.groves.map{|x| [x.name, x.id]} %>
  <%= form.submit 'Save' %>
<% end %>

app/views/admin/students/_show.html.erb
<%= link_to("All #{resource.class.name.pluralize.capitalize}", send("admin_#{ resource_as_sym.to_s.pluralize}_path"), class: "btn btn-default") if current_user.admin? %>
<br><br>
<table class="table">
  <tr>
    <% collection_attributes.each do |header| %>
      <th><%= header.to_s.titleize %></th>
    <% end %>
    <th>Actions</th>
  </tr>
  <tr>
    <% form_attributes.each do |attr| %>
      <td><%= resource.send(attr) %></td>
    <% end %>
    <td id="<%= resource_as_sym %>-<%= resource.id %>">
      <div class="btn-group">

      <%= link_to 'Delete', admin_student_path(resource), method: 'delete', class: "btn btn-danger" %>
      <%= link_to 'Rebuild Schedule', admin_student_rebuild_schedule_path(resource), class: "btn btn-info" %>
      </div>
    </td>
  </tr>
</table>

<h2>Daily Schedule</h2>
<table class="table">
  <tr>
    <th>Start Time</th>
    <th>End Time</th>
    <th>Location</th>
    <th>Activity Name</th>
  </tr>
  <% resource.events.each do |event| %>
  <tr>
    <td><%= event.start_time.strftime("%I:%M %p") %></td>
    <td><%= event.end_time.strftime("%I:%M %p") %></td>
    <td><%= event.location.try(:name) %></td>
    <td><%= event.title %></td>
  </tr>
  <% end %>
</table>

app/views/admin/students/index.html.erb
<div class="container">
  <h2>Grove Playlist Manager</h2>
  <br>
  <table>
    <tr>
      <th>Student Name</th>
      <th></th>
    </tr>
    <%= render partial: "student", collection: @students %>
  </table>
</div>