config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'
  
  devise_for :users, controllers: {sessions: 'users/sessions',
                                   omniauth_callbacks: 'users/omniauth_callbacks'}
  root 'home#index'

  namespace :admin do
    get '/dashboard', controller: 'dashboard', action: 'show', as: :dashboard
    get '/grove-monitor', controller: 'grove_monitor', action: 'show', as: :grove_monitor
    get '/grove-monitor-all', controller: 'grove_monitor', action: 'index', as: :grove_monitor_all
    patch '/grove-monitor-all', controller: 'grove_monitor', action: 'update', as: :update_grove_monitor_all
    get '/grove-playlist-manager', controller: 'playlists', action: 'index', as: :grove_playlist_manager
    resources :groves
    resources :locations
    resources :focus_areas
    resources :teachers
    resources :students do
      get '/rebuild_schedule', action: 'rebuild_schedule'
      get '/playlist', controller: 'playlist_activities', action: 'index'
      resources :playlist_activities, except: [:show]
    end
    resources :activities
  end

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      namespace :admin do
        resources :students, only: [] do
          patch '/playlist_activities', controller: 'students/playlist_activities', action: 'update'
        end
      end
    end
  end

  post '/notifications', controller: 'callbacks/google', action: 'watch'

  get '/compass', controller: 'compass', action: 'show', as: :compass
  get '/logout', controller: 'compass', action: 'logout', as: :logout
  get '/checkin', to: 'compass#checkin'

  # sidekiq monitoring
  require 'sidekiq/web'
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/views/shared/_flash.html.erb
<div class=" container row flash">
  <div class="col-sm-12">
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %> alert-dismissible fade in" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <%= sanitize(value) %>
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <button class="navbar-toggle collapsed" type="button" data-toggle='collapse' data-target='#navbar-collapse-1'>
        <span class="sr-only"> Toggle navigation</span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to (image_tag "roots-logo.png", style:"width:190px;height:auto", class:"navbar-brand", alt:"roots logo"), root_path %>
    </div>

    <div class="collapse navbar-collapse" id="navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right" style="margin-top:9px">
        <li><%= link_to("Grove Configuration", admin_dashboard_path) if current_user.admin? %></li>
        <li><%= link_to "Log out", destroy_user_session_path, method: 'delete' %></li>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_sidebar.html.erb
<ul class='button-column'>
  <h4>School Configuration</h4>
  <li><%=link_to("Groves", admin_groves_path, class: "btn hollow-btn btn-block") if policy(:grove).index? %></li>
  <li><%=link_to("Locations", admin_locations_path, class: "btn hollow-btn btn-block") if policy(:location).index? %></li>
  <li><%=link_to("Teachers", admin_teachers_path, class: "btn hollow-btn btn-block") if policy(:teacher).index? %></li>
  <li><%=link_to("Students", admin_students_path, class: "btn hollow-btn btn-block") if policy(:student).index? %></li>
  <li><%=link_to("Focus Areas", admin_focus_areas_path, class: "btn hollow-btn btn-block") if policy(:focus_area).index? %></li>

  <hr>
  <h4>Grove Management</h4>
  <li><%=link_to "Grove Monitor", admin_grove_monitor_all_path,class: "btn hollow-btn btn-block" %></li>
  <li><%=link_to "Grove Playlist Manager", admin_grove_playlist_manager_path, class: "btn hollow-btn btn-block" %></li>
  <li><%=link_to("Activities", admin_activities_path, class: "btn hollow-btn btn-block") if policy(:activity).index? %></li>
</ul>