config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'
  
  devise_for :users, controllers: {sessions: 'users/sessions',
                                   omniauth_callbacks: 'users/omniauth_callbacks'}
  root 'home#index'

  namespace :admin do
    get '/dashboard', controller: 'dashboard', action: 'show', as: :dashboard
    get '/grove-monitor', controller: 'grove_monitor', action: 'show', as: :grove_monitor
    get '/grove-monitor-all', controller: 'grove_monitor', action: 'index', as: :grove_monitor_all
    patch '/grove-monitor-all', controller: 'grove_monitor', action: 'update', as: :update_grove_monitor_all
    get '/grove-playlist-manager', controller: 'playlists', action: 'index', as: :grove_playlist_manager
    resources :groves
    resources :locations
    resources :focus_areas
    resources :teachers
    resources :students do
      get '/rebuild_schedule', action: 'rebuild_schedule'
      get '/playlist', controller: 'playlist_activities', action: 'index'
      resources :playlist_activities, except: [:show]
    end
    resources :activities
  end

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      namespace :admin do
        resources :students, only: [] do
          patch '/playlist_activities', controller: 'students/playlist_activities', action: 'update'
        end
      end
    end
  end

  post '/notifications', controller: 'callbacks/google', action: 'watch'

  get '/compass', controller: 'compass', action: 'show', as: :compass
  get '/logout', controller: 'compass', action: 'logout', as: :logout
  get '/checkin', to: 'compass#checkin'

  # sidekiq monitoring
  require 'sidekiq/web'
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/controllers/admin/grove_monitor_controller.rb
class Admin::GroveMonitorController < ApplicationController

  def index
    authorize(:grove_monitor, :index?)
    @locations = Location.where(grove_id: current_user.grove_id)
  end

  def show
    authorize(:grove_monitor, :show?)
    # suggests a location
    if params[:name]
      @display_type = :location
      @grove_monitor_location = GroveMonitorLocation.new(params[:name])
      @students = @grove_monitor_location.expected
      @unexpected = @grove_monitor_location.unexpected
      @location = @grove_monitor_location.location
    else
      # suggests a status, eg; lost, absent
      @display_type = :status
      @students = current_user.grove.students.send(filter_params)
      @category = filter_params
    end
  end

  def update
    authorize(:grove_monitor, :index?)
    student = Student.find(params[:id])
    student.update(student_params)
    redirect_to admin_grove_monitor_path(filter: params[:filter],
                                         name: params[:name])
  end

  private

    def student_params
      params.require(:student).permit(:at_school)
    end

    def filter_params
      params[:filter]
    end
end

app/helpers/grove_monitor_helper.rb
module GroveMonitorHelper

  def showing_location?
    @display_type == :location
  end

  def showing_status?
    @display_type == :status
  end

  def category_header
    case @display_type
      when :location then category_tag( @location.name.titleize)
      when :status then category_tag("#{@category.titleize} Students")
      else category_tag('Students')
    end
  end

  protected

  def category_tag(text)
    content_tag(:h2, text)
  end
end

app/views/admin/grove_monitor/_student.html.erb
<div class="col-md-3 col-sm-6 student">
  <div id="studentGM-<%= student.id %>" class="<%= student.scanned_in? ? "scanned-in": "enroute" %>">
    <h3><%= student.name %></h3>
    <%= image_tag student.google_image, class: "student-image" if student.google_image %>
    <% if student.at_school %>
      <%= link_to "Mark as Absent", admin_update_grove_monitor_all_path(id: student.id, student: { at_school: false }, filter: params[:filter], name: params[:name]), method: :patch, class: "btn btn-default" %>
      <% else %>
      <%= link_to "Mark as Present", admin_update_grove_monitor_all_path(id: student.id, student: { at_school: true }, filter: params[:filter], name: params[:name]), method: :patch, class: "btn btn-default" %>
    <% end %>
  </div>
</div>

app/views/admin/grove_monitor/index.html.erb
<ul class="nav nav-pills pull-right">
  <li role="presentation" class="active"><%= link_to "Absent", admin_grove_monitor_path(filter: :absent) %></li>
  <li role="presentation" class="active"><%= link_to "Lost", admin_grove_monitor_path(filter: :lost) %></li>
</ul>
<div class="grove-monitor text-center">
  <h2>Grove Monitor</h2>
</div>

<div class="row collection">
  <% @locations.each do |location| %>
    <div class="col-md-3 col-sm-6 single">
      <h2><%= link_to location.name.titleize, admin_grove_monitor_path({filter: :location, name: location.name}) %></h2>
      <%= link_to (image_tag location.image_url, class: "location-image"), admin_grove_monitor_path({filter: :location, name: location.name}) %>
    </div>
  <% end %>
</div>

app/views/admin/grove_monitor/show.html.erb
<ul class="nav nav-pills pull-right">

  <li role="presentation" class="active">
    <%= link_to "Back to Grove Monitor", admin_grove_monitor_all_path %>
  </li>

  <% if @display_type == :location %>
    <li role="presentation" class="active">
      <%= link_to "Reprint QR code", admin_location_path(@location) %>
    </li>
  <% end %>

</ul>

<div class="grove-monitor text-center">
  <%= category_header %>
</div>

<div class="row collection">
  <%= render partial: "student", collection: @students %>
</div>

<%- if showing_location? && !@unexpected.empty? %>
  <div class="grove-monitor text-center">
    <h2>Unexpected</h2>
  </div>

  <div class="row collection unexpected">
    <%= render partial: "student", collection: @unexpected %>
  </div>
<% end %>